version: '3.4'

services:
  nyoetools:
    image: nyoetools
    volumes:
    #  - /home/user:/home/user # add your own volumes to this
    build:
      context: .
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./main.py
          target: /app/main.py
