services:
  nyoetools:
    image: nyoetools
    volumes:
    #  - /home/user:/home/user # add your own volumes to this
    build:
      context: .
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: 
            - .venv/
          
        - action: rebuild
          path: ./pyproject.toml
